### ISSUE TITLE
Docs-documentation

### ISSUE THREAD

**Issue by micropipette** [micropipette/studybot#25]

**Comment by itchono** [comment]
# Regular Usage
## Setup
* Basics of the bot {what it is, using it in DMs, servers}
* Making a sheet
## Commands
* Starting a quiz {+ future multiplayer}
* Explore
* Binding/sheets/unbinding
* Explore
* Invite
* Help Menu
## Support Server
* Join the server for help/suggestions

# Server Owners
* Adding bot to server
* Setting Prefix
* Setting binding permissions
